name: Semgrep Coverage Report

on:
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.
    
jobs:
  get-list-of-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests
        pip install pandas
        
    - name: Get list of repositories
      env:
        # Generate PAT with Read-Only access to all repos in your GH ORG
        PAT_READ_ONLY_CUSTOMER_REPO: ${{ secrets.PAT_READ_ONLY_CUSTOMER_REPO }}
        SEMGREP_API_WEB_TOKEN:  ${{ secrets.SEMGREP_API_WEB_TOKEN }}
        SEMGREP_DEPLOYMENT_SLUG: ${{ vars.SEMGREP_DEPLOYMENT_SLUG }}
        DEBUG_LEVEL: ${{ vars.COVERAGE_REPORT_DEBUG_LEVEL }}

      run: |
        import requests
        import os
        import pandas as pd
        import json
        import sys
        import logging

        # Function to convert debug level from string to logging module constant
        def get_debug_level(level_str):
            return {
                'DEBUG': logging.DEBUG,
                'INFO': logging.INFO,
                'WARNING': logging.WARNING,
                'ERROR': logging.ERROR,
                'CRITICAL': logging.CRITICAL
            }.get(level_str.upper(), logging.INFO) # Default to INFO if not matched

        # Read DEBUG_LEVEL from environment and set logging level
        debug_level_str = os.getenv('DEBUG_LEVEL', 'INFO') # Default to INFO if not set
        print(f'Debug Level set to: {debug_level_str}')
        logging.basicConfig(level=get_debug_level(debug_level_str), format='%(asctime)s - %(levelname)s - %(message)s')

        def is_repo_empty(repo_name, pat):
            """
            Check if a GitHub repository is empty using the GitHub API.
            """
            url = f"https://api.github.com/repos/{repo_name}/branches"
            headers = {"Authorization": f"token {pat}"}
        
            try:
                response = requests.get(url, headers=headers)
                response.raise_for_status()  # Raise an error for bad responses
        
                # Check if the list of branches is empty
                if response.json():
                    logging.info(f"The repository '{repo_name}' is not empty.")
                    return "Not Empty"
                else:
                    logging.info(f"The repository '{repo_name}' is empty.")
                    return "Empty"
            except requests.exceptions.RequestException as e:
                logging.error(f"An error occurred while checking the repository: {e}")
                return False  # Assuming False in case of an error
        
        
        # GitHub repository in the format "org_name/repo_name"
        full_repo_name = os.environ['GITHUB_REPOSITORY']

        # Extract the organization name
        org_name = full_repo_name.split('/')[0]
        logging.info(f"Organization Name: {org_name}")
        pat = os.environ['PAT_READ_ONLY_CUSTOMER_REPO']
        headers = {'Authorization': f'token {pat}'}

        repos = []
        page = 1
        while True:
            url = f'https://api.github.com/orgs/{org_name}/repos?page={page}&per_page=100'
            response = requests.get(url, headers=headers)
            logging.debug(f"Requesting list of repos in Org: {org_name}, page: {page}")
            logging.debug(f"Response Code: {response.status_code}")
            page_repos = response.json()
            if not page_repos:
                break
            repos.extend(page_repos)
            page += 1
        logging.debug(f"Read list of repos from GitHub API successful- number of repos = {len(repos)} ")
        
        # Read list of repos in daily.csv and weekly.csv
        daily_df = pd.read_csv('daily.csv', header=None)
        logging.debug(f"Daily.csv read successful- number of repos in daily.csv = {len(daily_df)} ")
        weekly_df = pd.read_csv('weekly.csv', header=None)
        logging.debug(f"Weekly.csv read successful- number of repos in weekly.csv = {len(weekly_df)} ")
        
        daily_repos = daily_df[0].tolist()
        logging.debug(f"daily_repos created- length = {len(daily_repos)} ")
        weekly_repos = weekly_df[0].tolist()
        logging.debug(f"weekly_repos created- length = {len(weekly_repos)} ")
        github_repos = [repo['name'] for repo in repos]
        logging.debug(f"github_repos created- length = {len(github_repos)} ")

        daily_repos_not_in_github_repos = [item for item in daily_repos if item not in github_repos]
        logging.debug(f"daily_repos_not_in_github_repos created- length = {len(daily_repos_not_in_github_repos)} ")
        weekly_repos_not_in_github_repos = [item for item in weekly_repos if item not in github_repos]
        logging.debug(f"weekly_repos_not_in_github_repos created- length = {len(weekly_repos_not_in_github_repos)} ")

        df_daily_repos_not_in_github_repos = pd.DataFrame(daily_repos_not_in_github_repos)
        df_weekly_repos_not_in_github_repos = pd.DataFrame(weekly_repos_not_in_github_repos)

        df_daily_repos_not_in_github_repos.to_csv('daily_repos_not_in_github_repos.csv', index=False)
        logging.debug("df_daily_repos_not_in_github_repos written to file")
        df_weekly_repos_not_in_github_repos.to_csv('weekly_repos_not_in_github_repos.csv', index=False)
        logging.debug("df_weekly_repos_not_in_github_repos written to file")

        headers = {"Accept": "application/json", "Authorization": "Bearer " + os.environ['SEMGREP_API_WEB_TOKEN']}
        params =  {"page_size": 3000}

        r = requests.get(f"https://semgrep.dev/api/v1/deployments/{os.environ['SEMGREP_DEPLOYMENT_SLUG']}/projects?page=0", params=params, headers=headers)
        if r.status_code != 200:
            logging.error("Getting list of projects from Semgrep failed - please check Semgrep API token")
            sys.exit(f'Get failed: {r.text}')
        
        logging.debug("Getting list of projects from Semgrep successful")
        
        semgrep_repos = json.loads(r.text)

        coverage_data = []
        
        for repo in repos:
            repo_name = repo['name']
            logging.debug(f"processing repo start- {repo_name}")
            repo_full_name = repo['full_name']
            created_at = repo['created_at']
            html_url = repo['html_url']
            repo_empty_state = is_repo_empty(repo_full_name, pat)

            latest_scan = None
            for sg_repo in semgrep_repos['projects']:
                if sg_repo['name'] == repo_full_name:
                    latest_scan = sg_repo['latest_scan_at']
                    break
            
            if latest_scan is None:
                logging.info(f"{repo_name} not scanned by Semgrep yet")
            
            daily_mark = 1 if repo_name in daily_repos else 0
            weekly_mark = 1 if repo_name in weekly_repos else 0
            not_covered = 1 if (daily_mark + weekly_mark == 0) else 0
            duplicate_scans = 1 if (daily_mark + weekly_mark == 2) else 0
            
            coverage_data.append([repo_name, daily_mark, weekly_mark, not_covered, duplicate_scans, latest_scan, created_at, html_url, repo_empty_state])
            logging.debug(f"processing repo end- {repo_full_name}: {repo_name} , {daily_mark}, {weekly_mark}, {not_covered}, {duplicate_scans}, {latest_scan}, {created_at}, {html_url}, {repo_empty_state}")

        
        coverage_df = pd.DataFrame(coverage_data, columns=['Repository', 'Daily', 'Weekly', 'Not Covered', 'Duplicate Scans', 'Latest Scan', 'Created At', 'URL', 'Is Repo Empty'])
        coverage_df.to_csv('coverage.csv', index=False)
      
      shell: python
      
    - name: Upload coverage.CSV as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-coverage-report.csv
        path: |
          daily_repos_not_in_github_repos.csv
          weekly_repos_not_in_github_repos.csv
          coverage.csv
